# serverless.yml

service: aws-serverless-express-application

provider:
  name: aws
  runtime: nodejs14.0.0
  stage: dev
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
